Config = {}
Config.defaultTargetIcon = 'fas fa-shopping-basket'
Config.defaultTargetLabel = 'Open Shop'

-- Deliveries
Config.ShopsInvJsonFile = 'shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 500
Config.RewardItem = 'cryptostick'
Config.Fuel = 'LegacyFuel'

Config.DeliveryLocations = {
	['main'] = { label = 'GO Postal', coords = Vector(69.0862, 127.6753, 79.2123) },
	['vehicleWithdraw'] = Vector(71.9318, 120.8389, 79.0823),
	['vehicleDeposit'] = Vector(62.7282, 124.9846, 79.0926),
	['stores'] = {}, -- auto generated
}

Config.Vehicles = {
	['boxville2'] = { ['label'] = 'Boxville StepVan', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
	['normal'] = {
		{ name = 'tosti',         price = 2,   amount = 50 },
		{ name = 'water_bottle',  price = 2,   amount = 50 },
		{ name = 'kurkakola',     price = 2,   amount = 50 },
		{ name = 'twerks_candy',  price = 2,   amount = 50 },
		{ name = 'snikkel_candy', price = 2,   amount = 50 },
		{ name = 'sandwich',      price = 2,   amount = 50 },
		{ name = 'beer',          price = 7,   amount = 50 },
		{ name = 'whiskey',       price = 10,  amount = 50 },
		{ name = 'vodka',         price = 12,  amount = 50 },
		{ name = 'bandage',       price = 100, amount = 50 },
		{ name = 'lighter',       price = 2,   amount = 50 },
		{ name = 'rolling_paper', price = 2,   amount = 5000 },
	},
	['liquor'] = {
		{ name = 'beer',    price = 7,  amount = 50 },
		{ name = 'whiskey', price = 10, amount = 50 },
		{ name = 'vodka',   price = 12, amount = 50 },
	},
	['hardware'] = {
		{ name = 'lockpick',          price = 200, amount = 50 },
		--{ name = 'weapon_wrench',     price = 250, amount = 250, },
		--{ name = 'weapon_hammer',     price = 250, amount = 250, },
		{ name = 'repairkit',         price = 250, amount = 50, requiredJob = { 'mechanic', 'police' } },
		{ name = 'screwdriverset',    price = 350, amount = 50 },
		{ name = 'phone',             price = 850, amount = 50 },
		{ name = 'radio',             price = 250, amount = 50 },
		{ name = 'binoculars',        price = 50,  amount = 50 },
		{ name = 'firework1',         price = 50,  amount = 50 },
		{ name = 'firework2',         price = 50,  amount = 50 },
		{ name = 'firework3',         price = 50,  amount = 50 },
		{ name = 'firework4',         price = 50,  amount = 50 },
		{ name = 'cleaningkit',       price = 150, amount = 150 },
		{ name = 'advancedrepairkit', price = 500, amount = 50, requiredJob = 'mechanic' },
	},
	['weedshop'] = {
		{ name = 'joint',          price = 10, amount = 50 },
		{ name = 'weed_nutrition', price = 20, amount = 50 },
		{ name = 'empty_weed_bag', price = 2,  amount = 1000 },
		{ name = 'rolling_paper',  price = 2,  amount = 1000 },
	},
	['gearshop'] = {
		{ name = 'diving_gear', price = 2500, amount = 10 },
		{ name = 'jerry_can',   price = 200,  amount = 50 },
	},
	['leisureshop'] = {
		{ name = 'parachute',   price = 2500, amount = 10 },
		{ name = 'binoculars',  price = 50,   amount = 50 },
		{ name = 'diving_gear', price = 2500, amount = 10 },
		{ name = 'diving_fill', price = 500,  amount = 10 },
	},
	['weapons'] = {
		{ name = 'weapon_acm',        price = 0, amount = 250 },
		{ name = 'weapon_austro',     price = 0, amount = 250 },
		{ name = 'weapon_banshee',    price = 0, amount = 250 },
		{ name = 'weapon_bison',      price = 0, amount = 250 },
		{ name = 'weapon_cs446',      price = 0, amount = 250 },
		{ name = 'weapon_condor',     price = 0, amount = 250 },
		{ name = 'weapon_convert',    price = 0, amount = 250 },
		{ name = 'weapon_db12',       price = 0, amount = 250 },
		{ name = 'weapon_dnc68',      price = 0, amount = 250 },
		{ name = 'weapon_fang',       price = 0, amount = 250 },
		{ name = 'weapon_fierro',     price = 0, amount = 250 },
		{ name = 'weapon_finisher',   price = 0, amount = 250 },
		{ name = 'weapon_freq',       price = 0, amount = 250 },
		{ name = 'weapon_gaston',     price = 0, amount = 250 },
		{ name = 'weapon_kal',        price = 0, amount = 250 },
		{ name = 'weapon_kfs',        price = 0, amount = 250 },
		{ name = 'weapon_ktk',        price = 0, amount = 250 },
		{ name = 'weapon_krink',      price = 0, amount = 250 },
		{ name = 'weapon_lws32',      price = 0, amount = 250 },
		{ name = 'weapon_n77',        price = 0, amount = 250 },
		{ name = 'weapon_mk4',        price = 0, amount = 250 },
		{ name = 'weapon_mirage',     price = 0, amount = 250 },
		{ name = 'weapon_mouflan',    price = 0, amount = 250 },
		{ name = 'weapon_orion',      price = 0, amount = 250 },
		{ name = 'weapon_pn99',       price = 0, amount = 250 },
		{ name = 'weapon_ppy',        price = 0, amount = 250 },
		{ name = 'weapon_patriot',    price = 0, amount = 250 },
		{ name = 'weapon_pitviper',   price = 0, amount = 250 },
		{ name = 'weapon_queen80',    price = 0, amount = 250 },
		{ name = 'weapon_remi',       price = 0, amount = 250 },
		{ name = 'weapon_roger',      price = 0, amount = 250 },
		{ name = 'weapon_roma12',     price = 0, amount = 250 },
		{ name = 'weapon_ronin777',   price = 0, amount = 250 },
		{ name = 'weapon_sabra',      price = 0, amount = 250 },
		{ name = 'weapon_sovwhisper', price = 0, amount = 250 },
		{ name = 'weapon_vulcan',     price = 0, amount = 250 },
		{ name = 'weapon_flashlight', price = 0, amount = 250 },
	},
	['prison'] = {
		{ name = 'sandwich',     price = 4, amount = 50 },
		{ name = 'water_bottle', price = 4, amount = 50 },
	},
	['police'] = {
		-- { name = 'weapon_pistol',       price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
		-- { name = 'weapon_stungun',      price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
		-- { name = 'weapon_pumpshotgun',  price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
		-- { name = 'weapon_smg',          price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', label = '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
		-- { name = 'weapon_carbinerifle', price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = '3x Scope' }, } } },
		-- { name = 'weapon_nightstick',   price = 0, amount = 50 },
		-- { name = 'weapon_flashlight',   price = 0, amount = 50 },
		{ name = 'pistol_ammo',        price = 0, amount = 50 },
		{ name = 'smg_ammo',           price = 0, amount = 50 },
		{ name = 'shotgun_ammo',       price = 0, amount = 50 },
		{ name = 'rifle_ammo',         price = 0, amount = 50 },
		{ name = 'handcuffs',          price = 0, amount = 50 },
		{ name = 'empty_evidence_bag', price = 0, amount = 50 },
		{ name = 'police_stormram',    price = 0, amount = 50 },
		{ name = 'armor',              price = 0, amount = 50 },
		{ name = 'radio',              price = 0, amount = 50 },
		{ name = 'heavyarmor',         price = 0, amount = 50 },
	},
	['ambulance'] = {
		{ name = 'radio',       price = 0, amount = 50 },
		{ name = 'bandage',     price = 0, amount = 50 },
		{ name = 'painkillers', price = 0, amount = 50 },
		{ name = 'firstaid',    price = 0, amount = 50 },
		--{ name = 'weapon_flashlight',       price = 0, amount = 50, },
		--{ name = 'weapon_fireextinguisher', price = 0, amount = 50, },
	},
	['mechanic'] = {
		{ name = 'veh_toolbox',       price = 0, amount = 50 },
		{ name = 'veh_armor',         price = 0, amount = 50 },
		{ name = 'veh_brakes',        price = 0, amount = 50 },
		{ name = 'veh_engine',        price = 0, amount = 50 },
		{ name = 'veh_suspension',    price = 0, amount = 50 },
		{ name = 'veh_transmission',  price = 0, amount = 50 },
		{ name = 'veh_turbo',         price = 0, amount = 50 },
		{ name = 'veh_interior',      price = 0, amount = 50 },
		{ name = 'veh_exterior',      price = 0, amount = 50 },
		{ name = 'veh_wheels',        price = 0, amount = 50 },
		{ name = 'veh_neons',         price = 0, amount = 50 },
		{ name = 'veh_xenons',        price = 0, amount = 50 },
		{ name = 'veh_tint',          price = 0, amount = 50 },
		{ name = 'veh_plates',        price = 0, amount = 50 },
		{ name = 'nitrous',           price = 0, amount = 50 },
		{ name = 'tunerlaptop',       price = 0, amount = 50 },
		{ name = 'repairkit',         price = 0, amount = 50 },
		{ name = 'advancedrepairkit', price = 0, amount = 50 },
		{ name = 'tirerepairkit',     price = 0, amount = 50 },
	},
}

Config.Locations = {
	['minimart'] = {
		['label'] = 'MiniMart',
		['coords'] = Vector(-2322.078254, 15228.652227, -299.849995),
		['heading'] = 175,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['normal'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(26.45, -1315.51, 29.62),
		['useStock'] = false,
	},
	--[[ ['hansons'] = {
		['label'] = 'Hansons',
		['coords'] = Vector(16745.4, -46823.2, 171.6),
		['heading'] = 88,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['normal'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-40.51, -1747.45, 29.29),
	},
	['eastside'] = {
		['label'] = 'Eastside Market',
		['coords'] = Vector(-54567.0, -41338.1, 284.1),
		['heading'] = -108,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['normal'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-40.51, -1747.45, 29.29),
	},
	['fastfood'] = {
		['label'] = 'Fast Food',
		['coords'] = Vector(-30773.1, -224791.3, 205.9),
		['heading'] = -21,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['liquor'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-1226.92, -901.82, 12.28),
	},
	['fastfood1'] = {
		['label'] = 'Fast Food',
		['coords'] = Vector(-34032.6, -73824.6, 211.9),
		['heading'] = 160,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['liquor'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-1226.92, -901.82, 12.28),
	},
	['fastfood2'] = {
		['label'] = 'Fast Food',
		['coords'] = Vector(149626.4, -58093.0, 211.9),
		['heading'] = 2,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['liquor'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-1226.92, -901.82, 12.28),
	},
	['fastfood3'] = {
		['label'] = 'Fast Food',
		['coords'] = Vector(-139078.6, 126519.5, 191.3),
		['heading'] = 88,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['liquor'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-1226.92, -901.82, 12.28),
	},
	['fastfood4'] = {
		['label'] = 'Fast Food',
		['coords'] = Vector(119952.8, 28478.3, 211.9),
		['heading'] = 37,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
		['targetIcon'] = 'fas fa-shopping-basket',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['liquor'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-1226.92, -901.82, 12.28),
	},
	['gunshop'] = {
		['label'] = 'Gun Shop',
		['coords'] = Vector(-2053.6, -89885.1, 206.7),
		['heading'] = 178,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Gun Shop',
		['products'] = Config.Products['weapons'],
		['showblip'] = true,
		['blipsprite'] = 110,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-660.61, -938.14, 21.83),
	},
	['gunshop1'] = {
		['label'] = 'Gun Shop',
		['coords'] = Vector(53952.9, -192375.5, 194.2),
		['heading'] = 124,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Gun Shop',
		['products'] = Config.Products['weapons'],
		['showblip'] = true,
		['blipsprite'] = 110,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-660.61, -938.14, 21.83),
	},
	['gunshop2'] = {
		['label'] = 'Gun Shop',
		['coords'] = Vector(69022.5, 197398.7, 194.2),
		['heading'] = -126,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Gun Shop',
		['products'] = Config.Products['weapons'],
		['showblip'] = true,
		['blipsprite'] = 110,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-660.61, -938.14, 21.83),
	},
	['gunshop3'] = {
		['label'] = 'Gun Shop',
		['coords'] = Vector(-139307.4, 184192.9, 190.0),
		['heading'] = 2,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Gun Shop',
		['products'] = Config.Products['weapons'],
		['showblip'] = true,
		['blipsprite'] = 110,
		['blipscale'] = 0.6,
		['blipcolor'] = 0,
		['delivery'] = Vector(-660.61, -938.14, 21.83),
	},

	-- ['weedshop'] = {
	--     ['label'] = 'Smoke On The Water',
	--     ['coords'] = Vector(-1168.26, -1573.2, 4.66),
	--     ['heading'] = Rotator(0, 0, 0),
	--     ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
	--     ['animation'] = 'WORLD_HUMAN_AA_SMOKE',
	--     ['radius'] = 1.5,
	--     ['targetIcon'] = 'fas fa-cannabis',
	--     ['targetLabel'] = 'Open Weed Shop',
	--     ['products'] = Config.Products['weedshop'],
	--     ['showblip'] = true,
	--     ['blipsprite'] = 140,
	--     ['blipscale'] = 0.8,
	--     ['blipcolor'] = 0,
	--     ['delivery'] = Vector(-1162.13, -1568.57, 4.39)
	-- },

	-- ['seaword'] = {
	--     ['label'] = 'Sea Word',
	--     ['coords'] = Vector(-1687.03, -1072.18, 13.15),
	--     ['heading'] = Rotator(0, 0, 0),
	--     ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
	--     ['animation'] = 'WORLD_HUMAN_STAND_IMPATIENT',
	--     ['radius'] = 1.5,
	--     ['targetIcon'] = 'fas fa-fish',
	--     ['targetLabel'] = 'Sea Word',
	--     ['products'] = Config.Products['gearshop'],
	--     ['showblip'] = true,
	--     ['blipsprite'] = 52,
	--     ['blipscale'] = 0.8,
	--     ['blipcolor'] = 0,
	--     ['delivery'] = Vector(-1674.18, -1073.7, 13.15)
	-- },

	-- ['leisureshop'] = {
	--     ['label'] = 'Leisure Shop',
	--     ['coords'] = Vector(-1505.91, 1511.95, 115.29),
	--     ['heading'] = Rotator(0, 0, 0),
	--     ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
	--     ['animation'] = 'WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE',
	--     ['radius'] = 1.5,
	--     ['targetIcon'] = 'fas fa-leaf',
	--     ['targetLabel'] = 'Open Leisure Shop',
	--     ['products'] = Config.Products['leisureshop'],
	--     ['showblip'] = true,
	--     ['blipsprite'] = 52,
	--     ['blipscale'] = 0.8,
	--     ['blipcolor'] = 0,
	--     ['delivery'] = Vector(-1507.64, 1505.52, 115.29)
	-- },

	-- ['mechanic'] = {
	--     ['label'] = 'Mechanic Shop',
	--     ['coords'] = Vector(-343.66, -140.78, 39.02),
	--     ['products'] = Config.Products['mechanic'],
	--     ['delivery'] = Vector(-354.3936, -128.2882, 39.4307),
	--     ['requiredJob'] = 'mechanic',
	-- },

	-- ['ambulance'] = {
	--     ['label'] = 'Ambulance Shop',
	--     ['coords'] = Vector(309.93, -602.94, 43.29),
	--     ['heading'] = Rotator(0, 0, 0),
	--     ['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
	--     ['animation'] = 'WORLD_HUMAN_STAND_MOBILE',
	--     ['radius'] = 1.5,
	--     ['targetIcon'] = 'fas fa-hand',
	--     ['targetLabel'] = 'Open Armory',
	--     ['products'] = Config.Products['ambulance'],
	--     ['delivery'] = Vector(283.5821, -614.8570, 43.3792),
	--     ['requiredJob'] = 'ambulance'
	-- },

	['police'] = {
		['label'] = 'Police Shop',
		['coords'] = Vector(94931.0, -161470.7, 198.6),
		['heading'] = 132,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Armory',
		['products'] = Config.Products['police'],
		['delivery'] = Vector(459.0441, -1008.0366, 28.2627),
		['requiredJob'] = 'police',
	},
	['police1'] = {
		['label'] = 'Police Shop',
		['coords'] = Vector(45635.8, 239429.4, 198.6),
		['heading'] = -48,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Armory',
		['products'] = Config.Products['police'],
		['delivery'] = Vector(459.0441, -1008.0366, 28.2627),
		['requiredJob'] = 'police',
	},
	['police2'] = {
		['label'] = 'Police Shop',
		['coords'] = Vector(115873.2, 87536.2, 198.8),
		['heading'] = -98,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Armory',
		['products'] = Config.Products['police'],
		['delivery'] = Vector(459.0441, -1008.0366, 28.2627),
		['requiredJob'] = 'police',
	},
	['police3'] = {
		['label'] = 'Police Shop',
		['coords'] = Vector(-194487.4, 217043.2, 198.6),
		['heading'] = 16,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Armory',
		['products'] = Config.Products['police'],
		['delivery'] = Vector(459.0441, -1008.0366, 28.2627),
		['requiredJob'] = 'police',
	},
	['police4'] = {
		['label'] = 'Police Shop',
		['coords'] = Vector(20754.8, 11098.2, 208.8),
		['heading'] = 87,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-gun',
		['targetLabel'] = 'Open Armory',
		['products'] = Config.Products['police'],
		['delivery'] = Vector(459.0441, -1008.0366, 28.2627),
		['requiredJob'] = 'police',
	},

	['prison'] = {
		['label'] = 'Canteen Shop',
		['coords'] = Vector(-134199.4, -171627.3, 207.9),
		['heading'] = -65,
		['ped'] = '/CharacterCreator/CharacterAssets/Avatar_FBX/Body/Male/Mesh/Male_Full_Body',
		['animation'] = 'WORLD_HUMAN_COP_IDLES',
		['targetIcon'] = 'fas fa-clipboard',
		['targetLabel'] = 'Open Shop',
		['products'] = Config.Products['prison'],
		['showblip'] = true,
		['blipsprite'] = 52,
		['blipscale'] = 0.8,
		['blipcolor'] = 0,
		['delivery'] = Vector(1845.8175, 2585.9312, 45.6721)
	}, ]]
}
