Config = {
    Keybind = 'F3',
    Emotes = {
        ['Taunts'] = {
            YouHere = { name = 'You Here', animation_path = 'nanos-world::A_Mannequin_Taunt_YouHere', slot_type = AnimationSlotType.UpperBody, loop = true },
            Bow = { name = 'Bow', animation_path = 'nanos-world::A_Mannequin_Taunt_Bow', slot_type = AnimationSlotType.UpperBody, loop = true },
            ButtSlap_01 = { name = 'ButtSlap 01', animation_path = 'nanos-world::A_Mannequin_Taunt_ButtSlap_01', slot_type = AnimationSlotType.FullBody, loop = true },
            ButtSlap_02 = { name = 'ButtSlap 02', animation_path = 'nanos-world::A_Mannequin_Taunt_ButtSlap_02', slot_type = AnimationSlotType.FullBody, loop = true },
            CallMe = { name = 'Call Me', animation_path = 'nanos-world::A_Mannequin_Taunt_CallMe', slot_type = AnimationSlotType.UpperBody, loop = true },
            Chop = { name = 'Chop', animation_path = 'nanos-world::A_Mannequin_Taunt_Chop', slot_type = AnimationSlotType.UpperBody, loop = true },
            Clap = { name = 'Clap', animation_path = 'nanos-world::A_Mannequin_Taunt_Clap', slot_type = AnimationSlotType.UpperBody, loop = true },
            ComeAtMe = { name = 'Come At Me', animation_path = 'nanos-world::A_Mannequin_Taunt_ComeAtMe', slot_type = AnimationSlotType.UpperBody, loop = true },
            CrossArms = { name = 'Cross Arms', animation_path = 'nanos-world::A_Mannequin_Taunt_CrossArms', slot_type = AnimationSlotType.UpperBody, loop = true },
            Crutch = { name = 'Crutch', animation_path = 'nanos-world::A_Mannequin_Taunt_Crutch', slot_type = AnimationSlotType.UpperBody, loop = true },
            Dab = { name = 'Dab', animation_path = 'nanos-world::A_Mannequin_Taunt_Dab', slot_type = AnimationSlotType.UpperBody, loop = true },
            DustOff = { name = 'Dust Off', animation_path = 'nanos-world::A_Mannequin_Taunt_DustOff', slot_type = AnimationSlotType.UpperBody, loop = true },
            EarCom = { name = 'Ear Communication', animation_path = 'nanos-world::A_Mannequin_Taunt_EarCom', slot_type = AnimationSlotType.UpperBody, loop = true },
            EyesOnYou = { name = 'Eyes On You', animation_path = 'nanos-world::A_Mannequin_Taunt_EyesOnYou', slot_type = AnimationSlotType.UpperBody, loop = true },
            FacePalm = { name = 'Face Palm', animation_path = 'nanos-world::A_Mannequin_Taunt_FacePalm', slot_type = AnimationSlotType.UpperBody, loop = true },
            FingerGun = { name = 'Finger Gun', animation_path = 'nanos-world::A_Mannequin_Taunt_FingerGun', slot_type = AnimationSlotType.UpperBody, loop = true },
            FistCrush = { name = 'Fist Crush', animation_path = 'nanos-world::A_Mannequin_Taunt_FistCrush', slot_type = AnimationSlotType.UpperBody, loop = true },
            FistPump_01 = { name = 'Fist Pump 01', animation_path = 'nanos-world::A_Mannequin_Taunt_FistPump_01', slot_type = AnimationSlotType.UpperBody, loop = true },
            FistPump_02 = { name = 'Fist Pump 02', animation_path = 'nanos-world::A_Mannequin_Taunt_FistPump_02', slot_type = AnimationSlotType.UpperBody, loop = true },
            Flex_01 = { name = 'Flex 01', animation_path = 'nanos-world::A_Mannequin_Taunt_Flex_01', slot_type = AnimationSlotType.UpperBody, loop = true },
            Flex_02 = { name = 'Flex 02', animation_path = 'nanos-world::A_Mannequin_Taunt_Flex_02', slot_type = AnimationSlotType.UpperBody, loop = true },
            Flex_03 = { name = 'Flex 03', animation_path = 'nanos-world::A_Mannequin_Taunt_Flex_03', slot_type = AnimationSlotType.UpperBody, loop = true },
            Halt = { name = 'Halt', animation_path = 'nanos-world::A_Mannequin_Taunt_Halt', slot_type = AnimationSlotType.UpperBody, loop = true },
            HandOnHips = { name = 'Hand on Hips', animation_path = 'nanos-world::A_Mannequin_Taunt_HandOnHips', slot_type = AnimationSlotType.UpperBody, loop = true },
            HandPunch = { name = 'Hand Punch', animation_path = 'nanos-world::A_Mannequin_Taunt_HandPunch', slot_type = AnimationSlotType.UpperBody, loop = true },
            Heart = { name = 'Heart', animation_path = 'nanos-world::A_Mannequin_Taunt_Heart', slot_type = AnimationSlotType.UpperBody, loop = true },
            Jog = { name = 'Jog', animation_path = 'nanos-world::A_Mannequin_Taunt_Jog', slot_type = AnimationSlotType.FullBody, loop = true },
            Jojo = { name = 'Jojo', animation_path = 'nanos-world::A_Mannequin_Taunt_Jojo', slot_type = AnimationSlotType.UpperBody, loop = true },
            Knees = { name = 'Knees', animation_path = 'nanos-world::A_Mannequin_Taunt_Knees', slot_type = AnimationSlotType.UpperBody, loop = true },
            Kunfu = { name = 'Kungfu', animation_path = 'nanos-world::A_Mannequin_Taunt_Kunfu', slot_type = AnimationSlotType.UpperBody, loop = true },
            NeckSlit = { name = 'Neck Slit', animation_path = 'nanos-world::A_Mannequin_Taunt_NeckSlit', slot_type = AnimationSlotType.UpperBody, loop = true },
            OK = { name = 'OK', animation_path = 'nanos-world::A_Mannequin_Taunt_OK', slot_type = AnimationSlotType.UpperBody, loop = true },
            Point = { name = 'Point', animation_path = 'nanos-world::A_Mannequin_Taunt_Point', slot_type = AnimationSlotType.UpperBody, loop = true },
            Ponder = { name = 'Ponder', animation_path = 'nanos-world::A_Mannequin_Taunt_Ponder', slot_type = AnimationSlotType.UpperBody, loop = true },
            Praise = { name = 'Praise', animation_path = 'nanos-world::A_Mannequin_Taunt_Praise', slot_type = AnimationSlotType.UpperBody, loop = true },
            Salute_01 = { name = 'Salute 01', animation_path = 'nanos-world::A_Mannequin_Taunt_Salute_01', slot_type = AnimationSlotType.UpperBody, loop = true },
            Salute_02 = { name = 'Salute 02', animation_path = 'nanos-world::A_Mannequin_Taunt_Salute_02', slot_type = AnimationSlotType.UpperBody, loop = true },
            Savage = { name = 'Savage', animation_path = 'nanos-world::A_Mannequin_Taunt_Savage', slot_type = AnimationSlotType.UpperBody, loop = true },
            Shoosh = { name = 'Shoosh', animation_path = 'nanos-world::A_Mannequin_Taunt_Shoosh', slot_type = AnimationSlotType.UpperBody, loop = true },
            Shrug = { name = 'Shrug', animation_path = 'nanos-world::A_Mannequin_Taunt_Shrug', slot_type = AnimationSlotType.UpperBody, loop = true },
            Streach = { name = 'Stretch', animation_path = 'nanos-world::A_Mannequin_Taunt_Streach', slot_type = AnimationSlotType.UpperBody, loop = true },
            Sweat = { name = 'Sweat', animation_path = 'nanos-world::A_Mannequin_Taunt_Sweat', slot_type = AnimationSlotType.UpperBody, loop = true },
            TheHeavins = { name = 'The Heavins', animation_path = 'nanos-world::A_Mannequin_Taunt_TheHeavins', slot_type = AnimationSlotType.UpperBody, loop = true },
            ThumbsDown = { name = 'Thumbs Down', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsDown', slot_type = AnimationSlotType.UpperBody, loop = true },
            ThumbsOnEars = { name = 'Thumbs on Ears', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsOnEars', slot_type = AnimationSlotType.UpperBody, loop = true },
            ThumbsUp_01 = { name = 'Thumbs Up 01', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsUp_01', slot_type = AnimationSlotType.UpperBody, loop = true },
            ThumbsUp_02 = { name = 'Thumbs Up 02', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsUp_02', slot_type = AnimationSlotType.UpperBody, loop = true },
            Victory = { name = 'Victory', animation_path = 'nanos-world::A_Mannequin_Taunt_Victory', slot_type = AnimationSlotType.UpperBody, loop = true },
            Watch = { name = 'Watch', animation_path = 'nanos-world::A_Mannequin_Taunt_Watch', slot_type = AnimationSlotType.UpperBody, loop = true },
            Wave = { name = 'Wave', animation_path = 'nanos-world::A_Mannequin_Taunt_Wave', slot_type = AnimationSlotType.UpperBody, loop = true },
        },
        ['Generic'] = {
            Body_Stretch_01 = { name = 'Body Stretch 1', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_01', slot_type = AnimationSlotType.UpperBody, loop = true },
            Body_Stretch_02 = { name = 'Body Stretch 2', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_02', slot_type = AnimationSlotType.UpperBody, loop = true },
            Body_Stretch_03 = { name = 'Body Stretch 3', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_03', slot_type = AnimationSlotType.UpperBody, loop = true },
            Body_Stretch_04 = { name = 'Body Stretch 4', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_04', slot_type = AnimationSlotType.UpperBody, loop = true },
            Bow_01 = { name = 'Bow 1', animation_path = 'nanos-world::A_Mannequin_Bow_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Bow_02 = { name = 'Bow 2', animation_path = 'nanos-world::A_Mannequin_Bow_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Brush_Of_Dust = { name = 'Brush of Dust', animation_path = 'nanos-world::A_Mannequin_Brush_Of_Dust', slot_type = AnimationSlotType.UpperBody, loop = false },
            Call_Guards = { name = 'Call Guards', animation_path = 'nanos-world::A_Mannequin_Call_Guards', slot_type = AnimationSlotType.UpperBody, loop = false },
            Call_Someone_01 = { name = 'Call Someone 1', animation_path = 'nanos-world::A_Mannequin_Call_Someone_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Call_Someone_02 = { name = 'Call Someone 2', animation_path = 'nanos-world::A_Mannequin_Call_Someone_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Check_Equipment_01 = { name = 'Check Equipment 1', animation_path = 'nanos-world::A_Mannequin_Check_Equipment_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Check_Equipment_02 = { name = 'Check Equipment 2', animation_path = 'nanos-world::A_Mannequin_Check_Equipment_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Check_Equipment_03 = { name = 'Check Equipment 3', animation_path = 'nanos-world::A_Mannequin_Check_Equipment_03', slot_type = AnimationSlotType.UpperBody, loop = false },
            Clap_01 = { name = 'Clap 1', animation_path = 'nanos-world::A_Mannequin_Clap_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Clap_02 = { name = 'Clap 2', animation_path = 'nanos-world::A_Mannequin_Clap_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Crowd_Cheer = { name = 'Crowd Cheer', animation_path = 'nanos-world::A_Mannequin_Crowd_Cheer', slot_type = AnimationSlotType.UpperBody, loop = false },
            Deep_Breath_Sad = { name = 'Deep Breath Sad', animation_path = 'nanos-world::A_Mannequin_Deep_Breath_Sad', slot_type = AnimationSlotType.UpperBody, loop = false },
            Dont_Know_02 = { name = 'Don\'t Know 2', animation_path = 'nanos-world::A_Mannequin_Don_t_Know_2', slot_type = AnimationSlotType.UpperBody, loop = false },
            Dont_Know = { name = 'Don\'t Know', animation_path = 'nanos-world::A_Mannequin_Dont_Know', slot_type = AnimationSlotType.UpperBody, loop = false },
            Drunk_Talk = { name = 'Drunk Talk', animation_path = 'nanos-world::A_Mannequin_Drunk_Talk', slot_type = AnimationSlotType.UpperBody, loop = false },
            Exercise_01 = { name = 'Exercise 1', animation_path = 'nanos-world::A_Mannequin_Exercise_01', slot_type = AnimationSlotType.UpperBody, loop = true },
            Exercise_02 = { name = 'Exercise 2', animation_path = 'nanos-world::A_Mannequin_Exercise_02', slot_type = AnimationSlotType.UpperBody, loop = true },
            Exercise_03 = { name = 'Exercise 3', animation_path = 'nanos-world::A_Mannequin_Exercise_03', slot_type = AnimationSlotType.UpperBody, loop = true },
            Fart = { name = 'Fart', animation_path = 'nanos-world::A_Mannequin_Fart', slot_type = AnimationSlotType.UpperBody, loop = false },
            Fixing_Something = { name = 'Fixing Something', animation_path = 'nanos-world::A_Mannequin_Fixing_Something', slot_type = AnimationSlotType.UpperBody, loop = false },
            Get_Here_01 = { name = 'Get Here 1', animation_path = 'nanos-world::A_Mannequin_Get_Here_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Get_Here_02 = { name = 'Get Here 2', animation_path = 'nanos-world::A_Mannequin_Get_Here_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Go_Away = { name = 'Go Away', animation_path = 'nanos-world::A_Mannequin_Go_Away', slot_type = AnimationSlotType.UpperBody, loop = false },
            Deal = { name = 'Deal', animation_path = 'nanos-world::A_Mannequin_Deal', slot_type = AnimationSlotType.UpperBody, loop = false },
            Head_Scratch = { name = 'Head Scratch', animation_path = 'nanos-world::A_Mannequin_Head_Scratch', slot_type = AnimationSlotType.UpperBody, loop = false },
            Hold_Baby = { name = 'Hold Baby', animation_path = 'nanos-world::A_Mannequin_Hold_Baby', slot_type = AnimationSlotType.UpperBody, loop = false },
            Idle_01 = { name = 'Idle 1', animation_path = 'nanos-world::A_Mannequin_Idle_01', slot_type = AnimationSlotType.UpperBody, loop = true },
            Idle_02 = { name = 'Idle 2', animation_path = 'nanos-world::A_Mannequin_Idle_02', slot_type = AnimationSlotType.UpperBody, loop = true },
            Idle_03 = { name = 'Idle 3', animation_path = 'nanos-world::A_Mannequin_Idle_03', slot_type = AnimationSlotType.UpperBody, loop = true },
            Idle_04 = { name = 'Idle 4', animation_path = 'nanos-world::A_Mannequin_Idle_04', slot_type = AnimationSlotType.UpperBody, loop = true },
            Idle_05 = { name = 'Idle 5', animation_path = 'nanos-world::A_Mannequin_Idle_05', slot_type = AnimationSlotType.UpperBody, loop = true },
            Idle_06 = { name = 'Idle 6', animation_path = 'nanos-world::A_Mannequin_Idle_06', slot_type = AnimationSlotType.UpperBody, loop = true },
            Itching_Body = { name = 'Itching Body', animation_path = 'nanos-world::A_Mannequin_Itching_Body', slot_type = AnimationSlotType.UpperBody, loop = false },
            Laugh = { name = 'Laugh', animation_path = 'nanos-world::A_Mannequin_Laugh', slot_type = AnimationSlotType.UpperBody, loop = false },
            Legs_Relax = { name = 'Legs Relax', animation_path = 'nanos-world::A_Mannequin_Legs_Relax', slot_type = AnimationSlotType.UpperBody, loop = false },
            Lets_Go = { name = 'Let\'s Go', animation_path = 'nanos-world::A_Mannequin_Lets_Go', slot_type = AnimationSlotType.UpperBody, loop = false },
            Look_Around = { name = 'Look Around', animation_path = 'nanos-world::A_Mannequin_Look_Around', slot_type = AnimationSlotType.UpperBody, loop = false },
            No = { name = 'No', animation_path = 'nanos-world::A_Mannequin_No', slot_type = AnimationSlotType.UpperBody, loop = false },
            Playing_Guitar = { name = 'Playing Guitar', animation_path = 'nanos-world::A_Mannequin_Playing_Guitar', slot_type = AnimationSlotType.UpperBody, loop = false },
            Salute = { name = 'Salute', animation_path = 'nanos-world::A_Mannequin_Salute', slot_type = AnimationSlotType.UpperBody, loop = false },
            Shout = { name = 'Shout', animation_path = 'nanos-world::A_Mannequin_Shout', slot_type = AnimationSlotType.UpperBody, loop = false },
            Show_Bicep = { name = 'Show Bicep', animation_path = 'nanos-world::A_Mannequin_Show_Bicep', slot_type = AnimationSlotType.UpperBody, loop = false },
            Showing_Goods_01 = { name = 'Showing Goods 01', animation_path = 'nanos-world::A_Mannequin_Showing_Goods_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Showing_Goods_02 = { name = 'Showing Goods 02', animation_path = 'nanos-world::A_Mannequin_Showing_Goods_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Sit_Bench = { name = 'Sit Bench', animation_path = 'nanos-world::A_Mannequin_Sit_Bench', slot_type = AnimationSlotType.UpperBody, loop = false },
            Smith_Working = { name = 'Smith Working', animation_path = 'nanos-world::A_Mannequin_Smith_Working', slot_type = AnimationSlotType.UpperBody, loop = false },
            Sneeze = { name = 'Sneeze', animation_path = 'nanos-world::A_Mannequin_Sneeze', slot_type = AnimationSlotType.UpperBody, loop = false },
            Stinky = { name = 'Stinky', animation_path = 'nanos-world::A_Mannequin_Stinky', slot_type = AnimationSlotType.UpperBody, loop = false },
            Take_Drink = { name = 'Take Drink', animation_path = 'nanos-world::A_Mannequin_Take_Drink', slot_type = AnimationSlotType.UpperBody, loop = false },
            Take_From_Floor = { name = 'Take From Floor', animation_path = 'nanos-world::A_Mannequin_Take_From_Floor', slot_type = AnimationSlotType.UpperBody, loop = false },
            Take_From_Table = { name = 'Take From Table', animation_path = 'nanos-world::A_Mannequin_Take_From_Table', slot_type = AnimationSlotType.UpperBody, loop = false },
            Talking_01 = { name = 'Talking 01', animation_path = 'nanos-world::A_Mannequin_Talking_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Talking_02 = { name = 'Talking 02', animation_path = 'nanos-world::A_Mannequin_Talking_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Talking_03 = { name = 'Talking 03', animation_path = 'nanos-world::A_Mannequin_Talking_03', slot_type = AnimationSlotType.UpperBody, loop = false },
            Thinking = { name = 'Thinking', animation_path = 'nanos-world::A_Mannequin_Thinking', slot_type = AnimationSlotType.UpperBody, loop = false },
            Throw_01 = { name = 'Throw 01', animation_path = 'nanos-world::A_Mannequin_Throw_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Throw_02 = { name = 'Throw 02', animation_path = 'nanos-world::A_Mannequin_Throw_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Triumph = { name = 'Triumph', animation_path = 'nanos-world::A_Mannequin_Triumph', slot_type = AnimationSlotType.UpperBody, loop = false },
            Washing_Window = { name = 'Washing Window', animation_path = 'nanos-world::A_Mannequin_Washing_Window', slot_type = AnimationSlotType.UpperBody, loop = false },
            Watching_Somewhere = { name = 'Watching Somewhere', animation_path = 'nanos-world::A_Mannequin_Watching_Somewhere', slot_type = AnimationSlotType.UpperBody, loop = false },
            Wave_01 = { name = 'Wave 01', animation_path = 'nanos-world::A_Mannequin_Wave_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            Wave_02 = { name = 'Wave 02', animation_path = 'nanos-world::A_Mannequin_Wave_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            Wave_03 = { name = 'Wave 03', animation_path = 'nanos-world::A_Mannequin_Wave_03', slot_type = AnimationSlotType.UpperBody, loop = false },
        },
        ['Actions'] = {
            Equip = { name = 'Equip', animation_path = 'nanos-world::AM_Mannequin_Equip', slot_type = AnimationSlotType.UpperBody, loop = false },
            Unequip = { name = 'Unequip', animation_path = 'nanos-world::AM_Mannequin_Unequip', slot_type = AnimationSlotType.UpperBody, loop = false },
            DoorOpen_01 = { name = 'Door Open 01', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_01', slot_type = AnimationSlotType.FullBody, loop = false },
            DoorOpen_02 = { name = 'Door Open 02', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_02', slot_type = AnimationSlotType.FullBody, loop = false },
            DoorOpen_03 = { name = 'Door Open 03', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_03', slot_type = AnimationSlotType.FullBody, loop = false },
            DoorOpen_04 = { name = 'Door Open 04', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_04', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        ['Melee'] = {
            Stab_Attack = { name = 'Stab_Attack', animation_path = 'nanos-world::AM_Mannequin_Melee_Stab_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
            Slash_Attack = { name = 'Slash Attack', animation_path = 'nanos-world::AM_Mannequin_Melee_Slash_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
            Bayonet_Stab_Attack = { name = 'Bayonet Stab', animation_path = 'nanos-world::AM_Mannequin_Melee_Bayonet_Stab_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
            Torch_Attack = { name = 'Torch Attack', animation_path = 'nanos-world::AM_Mannequin_Torch_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        ['Locomotion'] = {
            Standing_IdleWalkRun = { name = 'Standing IdleWalkRun', animation_path = 'nanos-world::BS_Mannequin_Standing_IdleWalkRun', slot_type = AnimationSlotType.FullBody, loop = false },
            Crouching_IdleWalkRun = { name = 'Crouching IdleWalkRun', animation_path = 'nanos-world::BS_Mannequin_Crouching_IdleWalkRun', slot_type = AnimationSlotType.FullBody, loop = false },
            Proning_IdleWalk = { name = 'Proning IdleWalk', animation_path = 'nanos-world::BS_Mannequin_Proning_IdleWalk', slot_type = AnimationSlotType.FullBody, loop = false },
            StandingToCrouching = { name = 'Transition Standing to Crouching', animation_path = 'nanos-world::A_Mannequin_StandingToCrouching', slot_type = AnimationSlotType.FullBody, loop = false },
            CrouchingToStanding = { name = 'Transition Crouching to Standing', animation_path = 'nanos-world::A_Mannequin_CrouchingToStanding', slot_type = AnimationSlotType.FullBody, loop = false },
            ProningToCrouching = { name = 'Transition Proning to Crouching', animation_path = 'nanos-world::A_Mannequin_ProningToCrouching', slot_type = AnimationSlotType.FullBody, loop = false },
            CrouchingToProne = { name = 'Transition Crouching to Prone', animation_path = 'nanos-world::A_Mannequin_CrouchingToProne', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        ['Roleplay'] = {
            Bandaging_self_wound = { name = 'Bandage', animation_path = 'rp-anims-k::Bandaging_self_wound', slot_type = AnimationSlotType.UpperBody, loop = false },
            Bandaging_someone_wound = { name = 'Bandage Other', animation_path = 'rp-anims-k::Bandaging_someone_wound', slot_type = AnimationSlotType.UpperBody, loop = false },
            Being_bandaging = { name = 'Be Bandaged', animation_path = 'rp-anims-k::Being_bandaging', slot_type = AnimationSlotType.UpperBody, loop = false },
            Doctor_Seating_Idle = { name = 'Doctor Seat Idle', animation_path = 'rp-anims-k::Doctor_Seating_Idle', slot_type = AnimationSlotType.FullBody, loop = false },
            Drinking = { name = 'Drink', animation_path = 'rp-anims-k::Drinking', slot_type = AnimationSlotType.UpperBody, loop = false },
            Eating_donut = { name = 'Eat', animation_path = 'rp-anims-k::Eating_donut', slot_type = AnimationSlotType.UpperBody, loop = false },
            HandDown_01 = { name = 'Hands Down 1', animation_path = 'rp-anims-k::HandDown_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            HandDown_02 = { name = 'Hands Down 2', animation_path = 'rp-anims-k::HandDown_02', slot_type = AnimationSlotType.UpperBody, loop = false },
            HandUp_01 = { name = 'Hands Up 1', animation_path = 'rp-anims-k::HandUp_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            HandUp_02 = { name = 'Hands Up 2', animation_path = 'rp-anims-k::HandUp_02', slot_type = AnimationSlotType.FullBody, loop = false },
            HandUp_Idle_01 = { name = 'Hands Up 1 Idle', animation_path = 'rp-anims-k::HandUp_Idle_01', slot_type = AnimationSlotType.UpperBody, loop = false },
            HandUp_Idle_02 = { name = 'Hands Up 2 Idle', animation_path = 'rp-anims-k::HandUp_Idle_02', slot_type = AnimationSlotType.FullBody, loop = false },
            Male_Lockpicking_Animation = { name = 'Lockpick', animation_path = 'rp-anims-k::Male_Lockpicking_Animation', slot_type = AnimationSlotType.FullBody, loop = false },
            Rescuscitating_Someone = { name = 'CPR', animation_path = 'rp-anims-k::Rescuscitating_Someone', slot_type = AnimationSlotType.FullBody, loop = true },
            Talking_on_police_radio = { name = 'Radio', animation_path = 'rp-anims-k::Talking_on_police_radio', slot_type = AnimationSlotType.UpperBody, loop = false },
            talking_radio_Idle = { name = 'Radio Idle', animation_path = 'rp-anims-k::talking_radio_Idle', slot_type = AnimationSlotType.UpperBody, loop = false },
            Using_a_Defibrillator_on_someone = { name = 'Defib', animation_path = 'rp-anims-k::Using_a_Defibrillator_on_someone', slot_type = AnimationSlotType.FullBody, loop = false },
            A_StuffMoney_01 = { name = 'Grab Money', animation_path = 'rp-anims-k::A_StuffMoney_01', slot_type = AnimationSlotType.FullBody, loop = true },
            A_JudgeHammer_Sit_Intro = { name = 'Judge Sit Intro', animation_path = 'rp-anims-k::A_JudgeHammer_Sit_Intro', slot_type = AnimationSlotType.FullBody, loop = false },
            A_JudgeHammer_Sit_Loop = { name = 'Judge Sit Loop', animation_path = 'rp-anims-k::A_JudgeHammer_Sit_Loop', slot_type = AnimationSlotType.FullBody, loop = false },
            A_JudgeHammer_Sit_Outro = { name = 'Judge Sit Outro', animation_path = 'rp-anims-k::A_JudgeHammer_Sit_Outro', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        ['Casino'] = {
            PlayingCardsLose2RM = { name = 'Playing Cards Lose 2', animation_path = 'rp-anims-k::AS_PlayingCardsLose2RM', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsLoseRM = { name = 'Playing Cards Lose', animation_path = 'rp-anims-k::AS_PlayingCardsLoseRM', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsWinRM = { name = 'Playing Cards Win', animation_path = 'rp-anims-k::AS_PlayingCardsWinsRM', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsWin2RM = { name = 'Playing Cards Win 2', animation_path = 'rp-anims-k::AS_PlayingCardsWins2RM', slot_type = AnimationSlotType.FullBody, loop = false },
            Security4RM = { name = 'Security 4', animation_path = 'rp-anims-k::AS_Security4RM', slot_type = AnimationSlotType.FullBody, loop = false },
            Waitress2RM = { name = 'Waitress 2', animation_path = 'rp-anims-k::AS_Waitress2RM', slot_type = AnimationSlotType.FullBody, loop = false },
            Waitress3RM = { name = 'Waitress 3', animation_path = 'rp-anims-k::AS_Waitress3RM', slot_type = AnimationSlotType.FullBody, loop = false },
            WaitressRM = { name = 'Waitress', animation_path = 'rp-anims-k::AS_WaitressRM', slot_type = AnimationSlotType.FullBody, loop = false },
            WinSlotsTookCoinsRM = { name = 'Slots Took Coins', animation_path = 'rp-anims-k::AS_WinSlotsTookCoinsRM', slot_type = AnimationSlotType.FullBody, loop = false },
            WinsTakesChipsRM = { name = 'Wins Takes Chips', animation_path = 'rp-anims-k::AS_WinsTakesChipsRM', slot_type = AnimationSlotType.FullBody, loop = false },
            Dealer = { name = 'Dealer', animation_path = 'rp-anims-k::AS_Dealer', slot_type = AnimationSlotType.FullBody, loop = false },
            Dealer2 = { name = 'Dealer 2', animation_path = 'rp-anims-k::AS_Dealer2', slot_type = AnimationSlotType.FullBody, loop = false },
            DealerIdle = { name = 'Dealer Idle', animation_path = 'rp-anims-k::AS_DealerIdle', slot_type = AnimationSlotType.FullBody, loop = false },
            DealerRevealsCard = { name = 'Dealer Reveals Card', animation_path = 'rp-anims-k::AS_DealerRevealsCard', slot_type = AnimationSlotType.FullBody, loop = false },
            DealerSpinsRoulette = { name = 'Dealer Spins Roulette', animation_path = 'rp-anims-k::AS_DealerSpinsRoulette', slot_type = AnimationSlotType.FullBody, loop = false },
            DealingCards = { name = 'Dealing Cards', animation_path = 'rp-anims-k::AS_DealingCards', slot_type = AnimationSlotType.FullBody, loop = false },
            DealingCards2 = { name = 'Dealing Cards 2', animation_path = 'rp-anims-k::AS_DealingCards2', slot_type = AnimationSlotType.FullBody, loop = false },
            LoseSlots = { name = 'Lose Slots', animation_path = 'rp-anims-k::AS_LoseSlots', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCards = { name = 'Playing Cards', animation_path = 'rp-anims-k::AS_PlayingCards', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsLose = { name = 'Playing Cards Lose', animation_path = 'rp-anims-k::AS_PlayingCardsLose', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsLose2 = { name = 'Playing Cards Lose 2', animation_path = 'rp-anims-k::AS_PlayingCardsLose2', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsLose3 = { name = 'Playing Cards Lose 3', animation_path = 'rp-anims-k::AS_PlayingCardsLose3', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsLose4 = { name = 'Playing Cards Lose 4', animation_path = 'rp-anims-k::AS_PlayingCardsLose4', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsWins = { name = 'Playing Cards Wins', animation_path = 'rp-anims-k::AS_PlayingCardsWins', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsWins2 = { name = 'Playing Cards Wins 2', animation_path = 'rp-anims-k::AS_PlayingCardsWins2', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsWins3 = { name = 'Playing Cards Wins 3', animation_path = 'rp-anims-k::AS_PlayingCardsWins3', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCraps = { name = 'Playing Craps', animation_path = 'rp-anims-k::AS_PlayingCraps', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCrapsLose = { name = 'Playing Craps Lose', animation_path = 'rp-anims-k::AS_PlayingCrapsLose', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCrapsWins = { name = 'Playing Craps Wins', animation_path = 'rp-anims-k::AS_PlayingCrapsWins', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCrapsWins2 = { name = 'Playing Craps Wins 2', animation_path = 'rp-anims-k::AS_PlayingCrapsWins2', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingSlots = { name = 'Playing Slots', animation_path = 'rp-anims-k::AS_PlayingSlots', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingSlots2 = { name = 'Playing Slots 2', animation_path = 'rp-anims-k::AS_PlayingSlots2', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingSlots3 = { name = 'Playing Slots 3', animation_path = 'rp-anims-k::AS_PlayingSlots3', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingSlots5 = { name = 'Playing Slots 5', animation_path = 'rp-anims-k::AS_PlayingSlots5', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsAddsChips = { name = 'Playing Cards Adds Chips', animation_path = 'rp-anims-k::AS_PlayingCardsAddsChips', slot_type = AnimationSlotType.FullBody, loop = false },
            PlayingCardsAddsChips2 = { name = 'Playing Cards Adds Chips 2', animation_path = 'rp-anims-k::AS_PlayingCardsAddsChips2', slot_type = AnimationSlotType.FullBody, loop = false },
            Security = { name = 'Security', animation_path = 'rp-anims-k::AS_Security', slot_type = AnimationSlotType.FullBody, loop = false },
            Security2 = { name = 'Security 2', animation_path = 'rp-anims-k::AS_Security2', slot_type = AnimationSlotType.FullBody, loop = false },
            Security3 = { name = 'Security 3', animation_path = 'rp-anims-k::AS_Security3', slot_type = AnimationSlotType.FullBody, loop = false },
            Security4 = { name = 'Security 4', animation_path = 'rp-anims-k::AS_Security4', slot_type = AnimationSlotType.FullBody, loop = false },
            Waitress = { name = 'Waitress', animation_path = 'rp-anims-k::AS_Waitress', slot_type = AnimationSlotType.FullBody, loop = false },
            Waitress2 = { name = 'Waitress 2', animation_path = 'rp-anims-k::AS_Waitress2', slot_type = AnimationSlotType.FullBody, loop = false },
            Waitress3 = { name = 'Waitress 3', animation_path = 'rp-anims-k::AS_Waitress3', slot_type = AnimationSlotType.FullBody, loop = false },
            Watcher = { name = 'Watcher', animation_path = 'rp-anims-k::AS_Watcher', slot_type = AnimationSlotType.FullBody, loop = false },
            Watcher2 = { name = 'Watcher 2', animation_path = 'rp-anims-k::AS_Watcher2', slot_type = AnimationSlotType.FullBody, loop = false },
            Watcher3 = { name = 'Watcher 3', animation_path = 'rp-anims-k::AS_Watcher3', slot_type = AnimationSlotType.FullBody, loop = false },
            Watcher4 = { name = 'Watcher 4', animation_path = 'rp-anims-k::AS_Watcher4', slot_type = AnimationSlotType.FullBody, loop = false },
            Watcher5 = { name = 'Watcher 5', animation_path = 'rp-anims-k::AS_Watcher5', slot_type = AnimationSlotType.FullBody, loop = false },
            WinSlots = { name = 'Win Slots', animation_path = 'rp-anims-k::AS_WinSlots', slot_type = AnimationSlotType.FullBody, loop = false },
            WinSlotsTookCoins = { name = 'Win Slots Took Coins', animation_path = 'rp-anims-k::AS_WinSlotsTookCoins', slot_type = AnimationSlotType.FullBody, loop = false },
            WinsTakesChips = { name = 'Wins Takes Chips', animation_path = 'rp-anims-k::AS_WinsTakesChips', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        ['FearNFrights'] = {
            Alertness = { name = ' Alertness', animation_path = 'rp-anims-k::AS_Alertness', slot_type = AnimationSlotType.FullBody, loop = false },
            AlertnessAndBoom = { name = ' Alertness and Boom', animation_path = 'rp-anims-k::AS_AlertnessAndBoom', slot_type = AnimationSlotType.FullBody, loop = false },
            Alertness2 = { name = ' Alertness 2', animation_path = 'rp-anims-k::AS_Alertness2', slot_type = AnimationSlotType.FullBody, loop = false },
            StealthilyAfraid2 = { name = ' Stealthily Afraid 2', animation_path = 'rp-anims-k::AS_AS_StealthilyAfraid2', slot_type = AnimationSlotType.FullBody, loop = false },
            StealthilyAfraid2RM = { name = ' Stealthily Afraid 2 RM', animation_path = 'rp-anims-k::AS_AS_StealthilyAfraid2RM', slot_type = AnimationSlotType.FullBody, loop = false },
            BoundHostage = { name = ' Bound Hostage', animation_path = 'rp-anims-k::AS_BoundHostage', slot_type = AnimationSlotType.FullBody, loop = false },
            DontDoThis = { name = ' Dont Do This', animation_path = 'rp-anims-k::AS_DontDoThis', slot_type = AnimationSlotType.FullBody, loop = false },
            DontDoThis2 = { name = ' Dont Do This 2', animation_path = 'rp-anims-k::AS_DontDoThis2', slot_type = AnimationSlotType.FullBody, loop = false },
            ExplosionNearby = { name = ' Explosion Nearby', animation_path = 'rp-anims-k::AS_ExplosionNearby', slot_type = AnimationSlotType.FullBody, loop = false },
            ExplosionNearby2 = { name = ' Explosion Nearby 2', animation_path = 'rp-anims-k::AS_ExplosionNearby2', slot_type = AnimationSlotType.FullBody, loop = false },
            ExplosionNearby2RM = { name = ' Explosion Nearby 2 RM', animation_path = 'rp-anims-k::AS_ExplosionNearby2RM', slot_type = AnimationSlotType.FullBody, loop = false },
            ExplosionNearbyRM = { name = ' Explosion Nearby RM', animation_path = 'rp-anims-k::AS_ExplosionNearbyRM', slot_type = AnimationSlotType.FullBody, loop = false },
            Hostage = { name = ' Hostage', animation_path = 'rp-anims-k::AS_Hostage', slot_type = AnimationSlotType.FullBody, loop = false },
            Hostage2 = { name = ' Hostage 2', animation_path = 'rp-anims-k::AS_Hostage2', slot_type = AnimationSlotType.FullBody, loop = false },
            LightFright = { name = ' Light Fright', animation_path = 'rp-anims-k::AS_LightFright', slot_type = AnimationSlotType.FullBody, loop = false },
            LightFright2 = { name = ' Light Fright 2', animation_path = 'rp-anims-k::AS_LightFright2', slot_type = AnimationSlotType.FullBody, loop = false },
            PleaseStop = { name = ' Please Stop', animation_path = 'rp-anims-k::AS_PleaseStop', slot_type = AnimationSlotType.FullBody, loop = false },
            PleaseStopRM = { name = ' Please Stop RM', animation_path = 'rp-anims-k::AS_PleaseStopRM', slot_type = AnimationSlotType.FullBody, loop = false },
            StealthilyAfraid = { name = ' Stealthily Afraid', animation_path = 'rp-anims-k::AS_StealthilyAfraid', slot_type = AnimationSlotType.FullBody, loop = false },
            StealthilyAfraidRM = { name = ' Stealthily Afraid RM', animation_path = 'rp-anims-k::AS_StealthilyAfraidRM', slot_type = AnimationSlotType.FullBody, loop = false },
            StealthyBoom = { name = ' Stealthy Boom', animation_path = 'rp-anims-k::AS_StealthyBoom', slot_type = AnimationSlotType.FullBody, loop = false },
            StealthyBoomRM = { name = ' Stealthy Boom RM', animation_path = 'rp-anims-k::AS_StealthyBoomRM', slot_type = AnimationSlotType.FullBody, loop = false },
            Supplication = { name = ' Supplication', animation_path = 'rp-anims-k::AS_Supplication', slot_type = AnimationSlotType.FullBody, loop = false },
            Supplication2 = { name = ' Supplication 2', animation_path = 'rp-anims-k::AS_Supplication2', slot_type = AnimationSlotType.FullBody, loop = false },
            Supplication3 = { name = ' Supplication 3', animation_path = 'rp-anims-k::AS_Supplication3', slot_type = AnimationSlotType.FullBody, loop = false },
            VigilanceAndFright = { name = ' Vigilance and Fright', animation_path = 'rp-anims-k::AS_VigilanceAndFright', slot_type = AnimationSlotType.FullBody, loop = false },
            VigilanceAndFright2 = { name = ' Vigilance and Fright 2', animation_path = 'rp-anims-k::AS_VigilanceAndFright2', slot_type = AnimationSlotType.FullBody, loop = false },
            WhatWasThat = { name = ' What Was That', animation_path = 'rp-anims-k::AS_WhatWasThat', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        ['Hostage'] = {
            HostageHandcuffRunBack = { name = 'Hostage Handcuff Run Back', animation_path = 'rp-anims-k::Hostage_Handcuff_Run_Back', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandcuffRunForward = { name = 'Hostage Handcuff Run Forward', animation_path = 'rp-anims-k::Hostage_Handcuff_Run_Forward', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandcuffTurn180 = { name = 'Hostage Handcuff Turn 180', animation_path = 'rp-anims-k::Hostage_Handcuff_Turn_180', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandcuffTurnLeft90 = { name = 'Hostage Handcuff Turn Left 90', animation_path = 'rp-anims-k::Hostage_Handcuff_TurnLeft_90', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandcuffTurnRight90 = { name = 'Hostage Handcuff Turn Right 90', animation_path = 'rp-anims-k::Hostage_Handcuff_TurnRight_90', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandcuffWalkBack = { name = 'Hostage Handcuff Walk Back', animation_path = 'rp-anims-k::Hostage_Handcuff_Walk_Back', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandcuffWalkForward = { name = 'Hostage Handcuff Walk Forward', animation_path = 'rp-anims-k::Hostage_Handcuff_Walk_Forward', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandsCuffedLayOnFloorEnd = { name = 'Hostage Hands Cuffed Lay On Floor End', animation_path = 'rp-anims-k::Hostage_HandsCuffed_LayOnFloor_End', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandsCuffedLayOnFloorLoop = { name = 'Hostage Hands Cuffed Lay On Floor Loop', animation_path = 'rp-anims-k::Hostage_HandsCuffed_LayOnFloor_Loop', slot_type = AnimationSlotType.FullBody, loop = true },
            HostageHandsCuffedLayOnFloorStart = { name = 'Hostage Hands Cuffed Lay On Floor Start', animation_path = 'rp-anims-k::Hostage_HandsCuffed_LayOnFloor_Start', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandsCuffedReleasedGetUp = { name = 'Hostage Hands Cuffed Released Get Up', animation_path = 'rp-anims-k::Hostage_HandsCuffed_ReleasedGetUp', slot_type = AnimationSlotType.FullBody, loop = false },
            HostageHandsCuffedReleasingTheVictim = { name = 'Hostage Hands Cuffed Releasing the Victim', animation_path = 'rp-anims-k::Hostage_HandsCuffed_ReleasingTheVictim', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandCuffedSitEnd = { name = 'Idle Handcuffed Sit End', animation_path = 'rp-anims-k::Idle_HandCuffed_Sit_End', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandCuffedSitLoop = { name = 'Idle Handcuffed Sit Loop', animation_path = 'rp-anims-k::Idle_HandCuffed_Sit_Loop', slot_type = AnimationSlotType.FullBody, loop = true },
            IdleHandCuffedSitStart = { name = 'Idle Handcuffed Sit Start', animation_path = 'rp-anims-k::Idle_HandCuffed_Sit_Start', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandcuffHostageKneelEnd = { name = 'Idle Handcuff Hostage Kneel End', animation_path = 'rp-anims-k::Idle_HandcuffHostage_Kneel_End', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandcuffHostageKneelLoop = { name = 'Idle Handcuff Hostage Kneel Loop', animation_path = 'rp-anims-k::Idle_HandcuffHostage_Kneel_Loop', slot_type = AnimationSlotType.FullBody, loop = true },
            IdleHandcuffHostageKneelStart = { name = 'Idle Handcuff Hostage Kneel Start', animation_path = 'rp-anims-k::Idle_HandcuffHostage_Kneel_Start', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandcuffHostageKneelToLayOnFloorTransition = { name = 'Idle Handcuff Hostage Kneel to Lay on Floor Transition', animation_path = 'rp-anims-k::Idle_HandcuffHostage_Kneel_To_LayOnFloor_Transition', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandsUpHostageKneelEnd = { name = 'Idle Hands Up Hostage Kneel End', animation_path = 'rp-anims-k::Idle_HandsUpHostage_Kneel_End', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandsUpHostageKneelLoop = { name = 'Idle Hands Up Hostage Kneel Loop', animation_path = 'rp-anims-k::Idle_HandsUpHostage_Kneel_Loop', slot_type = AnimationSlotType.FullBody, loop = true },
            IdleHandsUpHostageKneelStart = { name = 'Idle Hands Up Hostage Kneel Start', animation_path = 'rp-anims-k::Idle_HandsUpHostage_Kneel_Start', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleHandsUpHostageKneelToHandsCuffedKneelTransition = { name = 'Idle Hands Up Hostage Kneel to Hands Cuffed Kneel Transition', animation_path = 'rp-anims-k::Idle_HandsUpHostage_Kneel_To_HandsCuffed_Kneel_Transition', slot_type = AnimationSlotType.FullBody, loop = false },
            IdleStanding = { name = 'Idle Standing', animation_path = 'rp-anims-k::Idle_Standing', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedHandcuffHostageLoopVic = { name = 'Paired Handcuff Hostage Loop Vic', animation_path = 'rp-anims-k::Paired_HandcuffHostage_Loop_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedHandcuffHostageStartAtt = { name = 'Paired Handcuff Hostage Start Attacker', animation_path = 'rp-anims-k::Paired_HandcuffHostage_Start_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedHandcuffHostageStartVic = { name = 'Paired Handcuff Hostage Start Victim', animation_path = 'rp-anims-k::Paired_HandcuffHostage_Start_Vic', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageAimSpaceAllDirectionsAtt = { name = 'Paired Pistol Grab Hostage Aim Space All Directions Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_AllDirections_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceForwardAtt = { name = 'Paired Pistol Grab Hostage Aim Space Forward Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_Forward_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceForwardVic = { name = 'Paired Pistol Grab Hostage Aim Space Forward Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_Forward_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceForwardDownVic = { name = 'Paired Pistol Grab Hostage Aim Space Forward Down Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_ForwardDown_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceForwardUpVic = { name = 'Paired Pistol Grab Hostage Aim Space Forward Up Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_ForwardUp_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceLeftAtt = { name = 'Paired Pistol Grab Hostage Aim Space Left Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_Left_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceLeftVic = { name = 'Paired Pistol Grab Hostage Aim Space Left Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_Left_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceLeftDownAtt = { name = 'Paired Pistol Grab Hostage Aim Space Left Down Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_LeftDown_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceLeftDownVic = { name = 'Paired Pistol Grab Hostage Aim Space Left Down Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_LeftDown_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceLeftUpAtt = { name = 'Paired Pistol Grab Hostage Aim Space Left Up Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_LeftUp_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceLeftUpVic = { name = 'Paired Pistol Grab Hostage Aim Space Left Up Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_LeftUp_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceRightAtt = { name = 'Paired Pistol Grab Hostage Aim Space Right Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_Right_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceRightVic = { name = 'Paired Pistol Grab Hostage Aim Space Right Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_Right_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceRightDownAtt = { name = 'Paired Pistol Grab Hostage Aim Space Right Down Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_RightDown_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceRightDownVic = { name = 'Paired Pistol Grab Hostage Aim Space Right Down Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_RightDown_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceRightUpAtt = { name = 'Paired Pistol Grab Hostage Aim Space Right Up Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_RightUp_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageAimSpaceRightUpVic = { name = 'Paired Pistol Grab Hostage Aim Space Right Up Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_AimSpace_RightUp_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageShootAtt = { name = 'Paired Pistol Grab Hostage Shoot Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_Shoot_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageShootVic = { name = 'Paired Pistol Grab Hostage Shoot Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_Shoot_Vic', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageShootVicRootMotion = { name = 'Paired Pistol Grab Hostage Shoot Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_Shoot_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageTurnLeft90Att = { name = 'Paired Pistol Grab Hostage Turn Left 90 Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_TurnLeft90_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageTurnLeft90Vic = { name = 'Paired Pistol Grab Hostage Turn Left 90 Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_TurnLeft90_Vic', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageTurnLeft90VicRootMotion = { name = 'Paired Pistol Grab Hostage Turn Left 90 Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_TurnLeft90_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageTurnRight90Att = { name = 'Paired Pistol Grab Hostage Turn Right 90 Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_TurnRight90_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageTurnRight90Vic = { name = 'Paired Pistol Grab Hostage Turn Right 90 Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_TurnRight90_Vic', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageTurnRight90VicRootMotion = { name = 'Paired Pistol Grab Hostage Turn Right 90 Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_TurnRight90_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageWalkBackAtt = { name = 'Paired Pistol Grab Hostage Walk Back Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkBack_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkBackVic = { name = 'Paired Pistol Grab Hostage Walk Back Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkBack_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkBackVicRootMotion = { name = 'Paired Pistol Grab Hostage Walk Back Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkBack_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkForwardAtt = { name = 'Paired Pistol Grab Hostage Walk Forward Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkForward_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkForwardVic = { name = 'Paired Pistol Grab Hostage Walk Forward Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkForward_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkForwardVicRootMotion = { name = 'Paired Pistol Grab Hostage Walk Forward Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkForward_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkLeftAtt = { name = 'Paired Pistol Grab Hostage Walk Left Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkLeft_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkLeftVic = { name = 'Paired Pistol Grab Hostage Walk Left Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkLeft_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkLeftVicRootMotion = { name = 'Paired Pistol Grab Hostage Walk Left Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkLeft_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkRightAtt = { name = 'Paired Pistol Grab Hostage Walk Right Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkRight_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkRightVic = { name = 'Paired Pistol Grab Hostage Walk Right Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkRight_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageWalkRightVicRootMotion = { name = 'Paired Pistol Grab Hostage Walk Right Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostage_WalkRight_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageFromBehindStartAtt = { name = 'Paired Pistol Grab Hostage From Behind Start Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromBehind_Start_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageFromFrontEndAtt = { name = 'Paired Pistol Grab Hostage From Front End Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_End_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageFromFrontEndVic = { name = 'Paired Pistol Grab Hostage From Front End Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_End_Vic', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageFromFrontEndVicRootMotion = { name = 'Paired Pistol Grab Hostage From Front End Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_End_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageFromFrontLoopAtt = { name = 'Paired Pistol Grab Hostage From Front Loop Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_Loop_Att', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageFromFrontLoopVic = { name = 'Paired Pistol Grab Hostage From Front Loop Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_Loop_Vic', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageFromFrontLoopVicRootMotion = { name = 'Paired Pistol Grab Hostage From Front Loop Victim Root Motion', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_Loop_Vic_RootMotion', slot_type = AnimationSlotType.FullBody, loop = true },
            PairedPistolGrabHostageFromFrontStartAtt = { name = 'Paired Pistol Grab Hostage From Front Start Attacker', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_Start_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolGrabHostageFromFrontStartVic = { name = 'Paired Pistol Grab Hostage From Front Start Victim', animation_path = 'rp-anims-k::Paired_Pistol_GrabHostageFromFront_Start_Vic', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolHandsUpHostageKneelHeadShotExecutionAtt = { name = 'Paired Pistol Hands Up Hostage Kneel Head Shot Execution Attacker', animation_path = 'rp-anims-k::Paired_Pistol_HandsUpHostage_Kneel_HeadShotExecution_Att', slot_type = AnimationSlotType.FullBody, loop = false },
            PairedPistolHandsUpHostageKneelHeadShotExecutionVic = { name = 'Paired Pistol Hands Up Hostage Kneel Head Shot Execution Victim', animation_path = 'rp-anims-k::Paired_Pistol_HandsUpHostage_Kneel_HeadShotExecution_Vic', slot_type = AnimationSlotType.FullBody, loop = false },
            PistolIdleAim = { name = 'Pistol Idle Aim', animation_path = 'rp-anims-k::Pistol_Idle_Aim', slot_type = AnimationSlotType.UpperBody, loop = true },
            PistolIdleRelaxed = { name = 'Pistol Idle Relaxed', animation_path = 'rp-anims-k::Pistol_Idle_Relaxed', slot_type = AnimationSlotType.UpperBody, loop = true },
            PistolIdleSignalingGetDown = { name = 'Pistol Idle Signaling Get Down', animation_path = 'rp-anims-k::Pistol_Idle_Signaling_GetDown', slot_type = AnimationSlotType.UpperBody, loop = false },
            PistolIdleSignalingGetUp = { name = 'Pistol Idle Signaling Get Up', animation_path = 'rp-anims-k::Pistol_Idle_Signaling_GetUp', slot_type = AnimationSlotType.UpperBody, loop = false },
        },
        ['Crouch Pickups'] = {
            ItemPickupFromIdleCrouch45LH0cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH25cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH50cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH75cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH100cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH125cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH150cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH175cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45LH200cm = { name = 'Item Pickup from Idle Crouch 45 Left Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_LH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH0cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH25cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH50cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH75cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH100cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH125cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH150cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH175cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch45RH200cm = { name = 'Item Pickup from Idle Crouch 45 Right Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_45_RH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH0cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH25cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH50cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH75cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH100cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH125cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH150cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH175cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90LH200cm = { name = 'Item Pickup from Idle Crouch 90 Left Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_LH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH0cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH25cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH50cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH75cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH100cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH125cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH150cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH175cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouch90RH200cm = { name = 'Item Pickup from Idle Crouch 90 Right Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_90_RH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH25cm = { name = 'Item Pickup from Idle Crouch Left Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH50cm = { name = 'Item Pickup from Idle Crouch Left Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH75cm = { name = 'Item Pickup from Idle Crouch Left Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH100cm = { name = 'Item Pickup from Idle Crouch Left Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH125cm = { name = 'Item Pickup from Idle Crouch Left Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH150cm = { name = 'Item Pickup from Idle Crouch Left Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH175cm = { name = 'Item Pickup from Idle Crouch Left Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchLH200cm = { name = 'Item Pickup from Idle Crouch Left Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_LH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH0cm = { name = 'Item Pickup from Idle Crouch Right Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH25cm = { name = 'Item Pickup from Idle Crouch Right Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH50cm = { name = 'Item Pickup from Idle Crouch Right Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH75cm = { name = 'Item Pickup from Idle Crouch Right Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH100cm = { name = 'Item Pickup from Idle Crouch Right Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH125cm = { name = 'Item Pickup from Idle Crouch Right Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH150cm = { name = 'Item Pickup from Idle Crouch Right Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH175cm = { name = 'Item Pickup from Idle Crouch Right Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchRH200cm = { name = 'Item Pickup from Idle Crouch Right Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_RH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchThrow01 = { name = 'Item Pickup from Idle Crouch Throw 01', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_Throw_01', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleCrouchThrow02 = { name = 'Item Pickup from Idle Crouch Throw 02', animation_path = 'rp-anims-k::A_ItemPickup_fromIdleCrouch_Throw_02', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        ['Idle Pickups'] = {
            ItemPickupFromIdle45LH0cm = { name = 'Item Pickup from Idle 45 Left Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH25cm = { name = 'Item Pickup from Idle 45 Left Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH50cm = { name = 'Item Pickup from Idle 45 Left Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH75cm = { name = 'Item Pickup from Idle 45 Left Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH100cm = { name = 'Item Pickup from Idle 45 Left Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH125cm = { name = 'Item Pickup from Idle 45 Left Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH150cm = { name = 'Item Pickup from Idle 45 Left Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH175cm = { name = 'Item Pickup from Idle 45 Left Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45LH200cm = { name = 'Item Pickup from Idle 45 Left Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_LH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH0cm = { name = 'Item Pickup from Idle 45 Right Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH25cm = { name = 'Item Pickup from Idle 45 Right Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH50cm = { name = 'Item Pickup from Idle 45 Right Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH75cm = { name = 'Item Pickup from Idle 45 Right Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH100cm = { name = 'Item Pickup from Idle 45 Right Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH125cm = { name = 'Item Pickup from Idle 45 Right Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH150cm = { name = 'Item Pickup from Idle 45 Right Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH175cm = { name = 'Item Pickup from Idle 45 Right Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle45RH200cm = { name = 'Item Pickup from Idle 45 Right Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_45_RH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH0cm = { name = 'Item Pickup from Idle 90 Left Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH25cm = { name = 'Item Pickup from Idle 90 Left Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH50cm = { name = 'Item Pickup from Idle 90 Left Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH75cm = { name = 'Item Pickup from Idle 90 Left Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH100cm = { name = 'Item Pickup from Idle 90 Left Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH125cm = { name = 'Item Pickup from Idle 90 Left Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH150cm = { name = 'Item Pickup from Idle 90 Left Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH175cm = { name = 'Item Pickup from Idle 90 Left Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90LH200cm = { name = 'Item Pickup from Idle 90 Left Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_LH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH0cm = { name = 'Item Pickup from Idle 90 Right Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH25cm = { name = 'Item Pickup from Idle 90 Right Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH50cm = { name = 'Item Pickup from Idle 90 Right Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH75cm = { name = 'Item Pickup from Idle 90 Right Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH100cm = { name = 'Item Pickup from Idle 90 Right Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH125cm = { name = 'Item Pickup from Idle 90 Right Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH150cm = { name = 'Item Pickup from Idle 90 Right Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH175cm = { name = 'Item Pickup from Idle 90 Right Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdle90RH200cm = { name = 'Item Pickup from Idle 90 Right Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_90_RH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH25cm = { name = 'Item Pickup from Idle Left Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH50cm = { name = 'Item Pickup from Idle Left Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH75cm = { name = 'Item Pickup from Idle Left Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH100cm = { name = 'Item Pickup from Idle Left Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH125cm = { name = 'Item Pickup from Idle Left Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH150cm = { name = 'Item Pickup from Idle Left Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH175cm = { name = 'Item Pickup from Idle Left Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleLH200cm = { name = 'Item Pickup from Idle Left Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_LH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH0cm = { name = 'Item Pickup from Idle Right Hand 0cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_0cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH25cm = { name = 'Item Pickup from Idle Right Hand 25cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_25cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH50cm = { name = 'Item Pickup from Idle Right Hand 50cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_50cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH75cm = { name = 'Item Pickup from Idle Right Hand 75cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_75cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH100cm = { name = 'Item Pickup from Idle Right Hand 100cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_100cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH125cm = { name = 'Item Pickup from Idle Right Hand 125cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_125cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH150cm = { name = 'Item Pickup from Idle Right Hand 150cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_150cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH175cm = { name = 'Item Pickup from Idle Right Hand 175cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_175cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleRH200cm = { name = 'Item Pickup from Idle Right Hand 200cm', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_RH_200cm', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleThrow01 = { name = 'Item Pickup from Idle Throw 01', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_Throw_01', slot_type = AnimationSlotType.FullBody, loop = false },
            ItemPickupFromIdleThrow02 = { name = 'Item Pickup from Idle Throw 02', animation_path = 'rp-anims-k::A_ItemPickup_fromIdle_Throw_02', slot_type = AnimationSlotType.FullBody, loop = false },
        },
        -- New Entry Here
    }
}

return Config
